name: mariadb
services:
  mariadb:
    container_name: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - PGID=1000
      - PUID=1000
      - REMOTE_SQL=
      - TZ=America/Sao_Paulo
    hostname: mariadb
    image: linuxserver/mariadb:11.4.5
    ports:
      - target: 3306
        published: "3306"
        protocol: tcp
    restart: unless-stopped
    # volumes:
    #   - type: bind
    #     source: /homelab-mirror/casaos/volumes/AppData/mariadb/config
    #     target: /config
    networks:
      - default
networks:
  default:
    name: mariadb_default
